Repository falcosecurity/rules, pull requests merged in 2023-01, with the labels that each got.

#2 update(registry): update rules package names
  registry.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#5 update(registry): trigger index update
  registry.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#6 chore(registry.yaml): testing the CI
  registry.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#7 chore(registry.yaml): testing CI
  registry.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#9 new(registry/o): add config layer to falco rules artifacts
  build/registry/cmd.go
  build/registry/config_layer.go
  build/registry/go.mod
  build/registry/go.sum
  build/registry/oci.go
  build/registry/requirements.go
Labels: dco-signoff: yes, approved, size/XXL, lgtm

#10 fix(ci): also push major floating tag and pre release
  build/registry/tag.go
  build/registry/tag_test.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#11 fix(registry/config): set correct key for engine version in config layer
  build/registry/requirements.go
Labels: dco-signoff: yes, approved, lgtm, size/XS

#12 docs(RELEASE.md): add initial release guidelines
  RELEASE.md
Labels: dco-signoff: yes, approved, lgtm, size/M

#14 build(build/registry): bump falcoctl
  build/registry/go.mod
  build/registry/go.sum
Labels: dco-signoff: yes, approved, lgtm, size/XS

#18 fix(README.md): the repo is now official
  README.md
Labels: dco-signoff: yes, approved, lgtm, size/XS

#19 update(ci): update falcoctl repo to 0.3.0-rc5
  build/registry/go.mod
  build/registry/go.sum
Labels: dco-signoff: yes, approved, lgtm, size/XS

#21 update(ci): use an explicit role instead of a secret
  .github/workflows/release.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#22 docs(README.md): clarifications and improvements
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/S, area/documentation
