Repository falcosecurity/rules, pull requests merged in 2023-06, with the labels that each got.

#71 fix(ci): solve issues with create-comment
  .github/workflows/create-comment.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/build

#73 fix(ci): fix http request body in create-comment
  .github/workflows/create-comment.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/build

#78 docs(RELEASE.md): update versioning guidelines for patch releases
  RELEASE.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M, area/documentation

#79 fix(ci): publish a version check comment event with no changes
  .github/compare-rule-files.sh
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup, area/build

#81 vote: update(OWNERS): add incertum (Melissa Kilby) to approvers
  OWNERS
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/XS, area/documentation

#93 Support azurefile-csi as known_aks_mount_in_privileged_containers
  rules/falco_rules.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XS, area/rules
