Repository falcosecurity/rules, pull requests merged in 2023-03, with the labels that each got.

#34 update(falco_rules): disable three rules by default
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#20 new(rules): introduce rule to detect drop and execute pattern in cont…
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#26 Added dnf-automatic to list of rpm_binaries
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#27 merge the two docker_binaries into a single one, the first was overrided
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#37 fix(rules): fix ptrace attach and injection rule
  rules/falco_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/S, area/rules

#41 fix(rules): add authorized_server_binary list
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, area/rules
