Repository falcosecurity/rules, pull requests merged in 2023-07, with the labels that each got.

#102 cleanup(rules): initially tag all rules disabled by default w/ maturity_sandbox level
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/M, kind/cleanup, area/rules

#66 Introduce OCI artifacts signatures
  .github/workflows/release.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/registry, area/build

#103 cleanup(rules): initial transitions of some sandbox rules to incubating
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup, area/rules

#107 fix(ci): solve issues with docker
  .github/workflows/rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/build

#106 cleanup(rules): initial tagging of stable rules round1
  rules/falco_rules.yaml
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M, kind/cleanup, area/rules

#108 cleanup(rules): initial tagging of stable rules round2
  rules/falco_rules.yaml
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M, kind/cleanup, area/rules

#109 cleanup(rules): initial tagging of stable rules round3
  rules/falco_rules.yaml
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M, kind/cleanup, area/rules

#112 cleanup(rules): initial tagging of sandbox or incubating rules round2
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup

#113 cleanup(rules): initial tagging of sandbox or incubating rules round3
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup

#114 cleanup(rules): initial tagging of sandbox or incubating rules round4
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup

#110 cleanup(rules): initial tagging of stable rules round4
  rules/falco_rules.yaml
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M, kind/cleanup, area/rules

#116 new(ci): added github pages around rules overview file.
  .github/workflows/pages.yaml
  mkdocs.yml
  requirements.txt
  rules_inventory/rules_overview.md
Labels: kind/feature, dco-signoff: yes, approved, lgtm, area/documentation, size/XL

#117 fix(ci): fixed pages generation.
  .github/workflows/pages.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/documentation

#118 docs(.github): update PR template according to the new contrib guide
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/S, area/documentation

#120 cleanup(rules): initial tagging of sandbox or incubating rules round5
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup

#123 new(rules): initial tagging of PCI DSS and NIST related rules
  rules/falco_rules.yaml
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/S, kind/cleanup, area/rules

#124 cleanup(ci): adjust overview generator markdown
  .github/scripts/rules_overview_generator.py
Labels: dco-signoff: yes, approved, lgtm, size/S, area/documentation, kind/cleanup

#125 fix(rules): fix some syntax issues and some mitre assignments
  rules/falco_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/M, kind/cleanup

#122 cleanup(rules): adjust output fields wrt new style guide
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, area/rules, size/XL
