Repository falcosecurity/rules, pull requests merged in 2024-05, with the labels that each got.

#245 fix: change CVE-2024-3094 to match liblzma contain instead of endswith
  rules/falco-incubating_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/rules, area/maturity-incubating

#248 fix(.github/workflow): strict naming convention for changed rules files
  .github/workflows/rules.yaml
Labels: kind/bug, kind/documentation, dco-signoff: yes, approved, lgtm, size/S, area/build

#247 vote: Adding @darryk10 to rules approvers
  rules/OWNERS
Labels: dco-signoff: yes, approved, lgtm, size/XS

#250 chore(gha): add 0.38.0 to supported Falco versions
  .github/FALCO_VERSIONS
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XS, area/build

#249 Some minor fixes
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup, area/rules, area/maturity-stable
