Repository falcosecurity/rules, pull requests merged in 2024-03, with the labels that each got.

#231 update(sandbox): Added systemd to list of programs ignored when using BPF.
  rules/falco-sandbox_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#236 update(rules): cleanup k8s.gcr.io
  rules/falco-incubating_rules.yaml
  rules/falco-sandbox_rules.yaml
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S, kind/cleanup, area/rules, area/maturity-stable, area/maturity-incubating, area/maturity-sandbox

#234 chore(ci): adding YAML-Lint for falco rules
  .github/workflows/yaml-lint.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/S

#232 cleanup(rules-sandbox): remove old ref to k8s.gcr.io
  .github/workflows/yaml-lint.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup, area/maturity-sandbox

#237 update: add macro known_drop_and_execute_activities
  rules/falco_rules.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XS, area/rules, area/maturity-stable
