Repository falcosecurity/rules, pull requests merged in 2024-02, with the labels that each got.

#223 fix(ci): fixed pages CI.
  .github/workflows/pages.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/documentation

#228 update(ci): add Falco 0.37.1 to FALCO_VERSIONS.
  .github/FALCO_VERSIONS
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup

#227 chore: minor readme edits
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/S, area/documentation, kind/cleanup

#208 Update: bpf cmd format
  rules/falco-sandbox_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/rules, area/maturity-sandbox

#230 update(.github/FALCO_VERSIONS): unsupporting 0.37
  .github/FALCO_VERSIONS
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup, area/build
