Repository falcosecurity/rules, pull requests merged in 2024-06, with the labels that each got.

#252 fix: Missing % in "Unexpected UDP Traffic" output rule
  rules/falco-incubating_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, kind/cleanup, area/rules, area/maturity-incubating

#253 fix: fixed output issues within the ruleset
  rules/falco_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#254 fix: fixed output issues within the incubating ruleset
  rules/falco-incubating_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS, area/rules

#251 vote: update(OWNERS): add loresuso to approvers
  rules/OWNERS
Labels: dco-signoff: yes, approved, lgtm, size/XS

#255 fix: fixed output issues within the sandbox ruleset
  rules/falco-sandbox_rules.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S
