Repository falcosecurity/rules, pull requests merged in 2024-08, with the labels that each got.

#257 fix(incubating_rules): revert #508
  rules/falco-incubating_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/rules, area/maturity-incubating

#262 update(ci): add 0.38.1 and 0.38.2 as supported versions
  .github/FALCO_VERSIONS
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XS, area/build

#261 chore: upgrade py deps for rules_overview_generator
  .github/scripts/requirements.txt
Labels: dco-signoff: yes, approved, lgtm, size/XS, area/documentation, kind/cleanup
